### ISSUE TITLE
Team17 Review: VnV - Functional req. test for webcam error

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#50]
> FRT4-HW2
> Goal: Monitor web camera useability
> Input: User is currently within a progression course and camera error arises

It is not clear how you will make sure that the error is thrown (although this could be related to implementation details). Though there should be more information to make sure the error is introduced, and what kind of error the test process shall introduce for this situation.
Additionally, since this is an error handling test, it may be more suitable for a non functional requirement.

This issue was created by Team 17 as part of the VnV Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
This test case is about ensuring that the web camera is functional or usable for the user, and if it is not, they will be notified that this is the case. This is a function of the system (and corresponds to FR11 in our SRS document) so we think that this test is more suited to being a functional requirement test. 

Some system states that we think would trigger this error to occur during testing are things like if the camera is not connected properly, if the camera cannot detect anything from the users end due to it being out of range or focus etc. which once implemented should throw an error to the user that there is one of these issues with their camera set up. This should prompt them to attempt to fix the issue and try again. 

Thanks for the feedback!
