### ISSUE TITLE
Team17 Review: VnV - NFR test suggestion

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#51]
It may be helpful to make a test case testing the ease and efficiency of calibrating the webcam for sign recognitions, or testing the limits of at what angles or lighting conditions can the camera be used.

This issue was created by Team 17 as part of the VnV Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
There is currently a test case (NFRT1 - UT5 in relation to our Non-Functional Requirement UHR4) that tests for limiting factors of the camera recognition. During testing, if the camera is not connected properly, if the camera cannot detect anything from the users end due to it being out of range or focus etc. the system should throw an error to tell the user that there is one of these issues with their camera set up. This should prompt them to attempt to fix the specified issue and try again. We think that this test case is similar enough to what you are suggesting because if the camera cannot detect what the user is signing due to their angle or lighting, it will throw an error and the user will be notified.  

Thanks for the feedback!

![image](https://github.com/stanreee/sign-language-learning/assets/77757843/7d973853-58f1-4a38-92b7-4f28c10763e9)
