### ISSUE TITLE
Team17 Review: VnV - Safety testing

### ISSUE THREAD

**Issue by mohaanshpranjal** [stanreee/sign-language-learning#53]
Since there are login accounts which facilitate user privacy, it would be helpful to consider some tests on safety requirements.

This issue was created by Team 17 as part of the VnV Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks for the feedback! The development team has decided that allowing users to make an account in our application was out of scope for this project due to time constraints in making a user progression course. As a result, user account information and privacy will not be required for this application.
