### ISSUE TITLE
Team 17 Review: Design - MG Anticipated Changes and Modules 

### ISSUE THREAD

**Issue by AllisonRCook** [stanreee/sign-language-learning#69]
Great work! I noticed one of your anticipated changes, 'AC1' maps to a few modules. It might be good to look at altering the plan so that it maps to fewer modules or making a note as to why this is an exception. 

This issue was created by Team 17 as part of the Design Primary Review. Tagging marking TA as recommended @Lyuyang0130
[Review-Team17]

**Comment by CassieBaldin** [comment]
Thanks for the feedback! The reason this anticipated change maps to so many modules is because if we were to update the words or phrases used in our application then we would have to change the machine learning module and all other dependent modules.

I added a section above the table to explain this to other readers of the document now! 
You can view the changes here: d66292b

![image](https://github.com/stanreee/sign-language-learning/assets/77757843/8e7ffcb7-8191-4c2b-abc4-8e5d696d25fe)
